version: "3.8"
services:
  backend:
    image: 390613096869.dkr.ecr.us-east-2.amazonaws.com/online-school-backend:latest
    environment:
      DOCKER_RUN: ${DOCKER_RUN:-true}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - database
    command: node /app/build/src/app.js

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pg-data-prod:/var/lib/postgresql/data
volumes:
  pg-data-prod: